import {
  Home,
  Package,
  ShoppingCart,
  Warehouse,
  Truck,
  Camera,
  BookOpen,
  MessageCircle,
  Calculator,
  Settings,
  Tag,
  ClipboardList,
  Receipt,
  GraduationCap,
  type LucideIcon,
} from "lucide-react";

export const MODULE_ICONS: Record<string, LucideIcon> = {
  inicio: Home,
  inventario: Package,
  ventas: ShoppingCart,
  pedidos: ClipboardList,
  retiros: Warehouse,
  repartos: Truck,
  evidencias: Camera,
  gastos: Receipt,
  capacitacion: GraduationCap,
  manuales: BookOpen,
  asistente: MessageCircle,
  calculadora: Calculator,
  etiquetas: Tag,
  administracion: Settings,
};
